server:
  port: 8091

spring:
  application:
    name: account-card-service
  cloud:
    config:
      enabled: false
  profiles:
    include: common

logging:
  level:
    com.creditqu.account_card_service: DEBUG

account-card:
  card:
    expiry-years: 5
    cvv-length: 3
    pin-length: 6
  virtual-account:
    bank-codes:
      - BNI
      - MANDIRI
      - BRI
      - BCA
    expiry-days: 30