server:
  port: 8092

spring:
  application:
    name: card-product-service
  cloud:
    config:
      enabled: false
  profiles:
    include: common

logging:
  level:
    com.creditqu.card_product_service: DEBUG